### ISSUE TITLE
version 1.4.0 breaks LDAP authentication by group

### ISSUE THREAD

**Issue by jharris4** [Alexandre-io/verdaccio-ldap#21]
I just updated from `1.3.0` to `1.4.0` and could no longer access any packages from my verdaccio server.

I get errors like:

`"status":403,"error":"user <user> is not allowed to access package <package>"`

My verdaccio `config.yaml` is setup to use the ldap groups to control access, something like:

```
packages:
  '@*/*':
    # scoped packages
    access: <ldap-group>
    publish: <ldap-group>
    proxy: npmjs
```

I downgraded back to `1.3.0` and everything started working again, so definitely looks like something broke in `1.4.0`
