### ISSUE TITLE
$authenticated doesn't work with verdaccio v2.7.4, ldap plugin 1.3.0 and node 10.1

### ISSUE THREAD

**Issue by kopax** [Alexandre-io/verdaccio-ldap#27]
I am trying to set `access: $authenticated` to the scope `'@someorg/*':` but I keep getting authenticated then the next request is anonymous.

Does anybody know about such a bug ? 

I am using : 

- verdaccio v2.7.4
- verdaccio-ldap v1.3.0 
- node v10.1.

This is my configuration:

```yml
storage: /verdaccio/storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldap://ldap.example.com"
      adminDn: "cn=readonly,dc=example,dc=com"
      adminPassword: "example"
      searchBase: "dc=example,dc=com"
      searchFilter: "(&(uid={{username}})(memberOf=cn=npm_users,ou=groups,dc=example,dc=com))"
      cache: False
      searchAttributes:
        - "*"
        - memberOf
      tlsOptions:
        rejectUnauthorized: False
    max_users: -1
  htpasswd:
    file: ./htpasswd
#   # Maximum amount of users allowed to register, defaults to "+inf".
#   # You can set this to -1 to disable registration.
#   # currently used only for deployment accounts
    max_users: 2

# a list of other known repositories we can talk to

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@someorg/*':
    # scoped packages
    access: $authenticated
    publish: npm_users
#    proxy: npmjs

  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}
web:
  enable: true
  title: Redacted
```

I am able to publish a scoped package in `@someorg/*` but no user can download it after:

```bash
 http <-- 200, user: dga(115.73.7.165 via 172.16.0.1), req: 'GET /@someorg%2fdeleteme', bytes: 0/3248
 http <-- 403, user: undefined(115.73.7.165 via 172.16.0.1), req: 'GET /@someorg%2fdeleteme/-/deleteme-0.0.4.tgz', error: unregistered users are not allowed to access package @someorg/deleteme

```

I have fixed my version of verdaccio and verdaccio-ldap because both latest version together doesn't work. Somebody on IRC shared me it's working version with ldap but mine is not working. I would gladly upgrade if maintainer could help.

**Comment by kopax** [comment]
There is not only authenticated but also ldap group used with OpenLDAP does not work correctly:

I am looking at 1.4.0 documentation and you have added 

```yml
      # If you are using groups, this is also needed
      groupDnProperty: 'cn',
      groupSearchBase: 'ou=groups,dc=myorg,dc=com',
      groupSearchFilter: '(memberUid={{dn}})',
```

This is not present in 1.3.0, and 1.4.0 is not functional. 

What are the way to configure ldap groups  with wich version please?

**Comment by Alexandre-io** [comment]
Could you try with the latest version (2.0.0) ? thanks!

**Comment by kopax** [comment]
Thanks @Alexandre-io , I have been able to configure properly.

Keep in mind that when updating groups **it is not required** to regenerate a npm token, and to update the UI visibility for any **access** perms, you will have to logout and login.

**Comment by kopax** [comment]
Authentication now pass, but with the following :  

```yml
storage: /verdaccio/storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldaps://ldap.example.com"
      adminDn: "cn=readonly,dc=example,dc=com"
      adminPassword: "example"
      searchBase: "dc=example,dc=com"
      searchFilter: "(&(uid={{username}})(memberOf=cn=npm_users,ou=npm,ou=groups,dc=example,dc=com))"
      # searchFilter: "(uid={{username}})"
      # # If you are using groups, this is also needed
      groupDnProperty: 'cn'
      groupSearchBase: 'ou=npm,ou=groups,dc=example,dc=com'
      searchAttributes: ['*', 'memberOf']
      # Optional
      cache: False
      tlsOptions:
        rejectUnauthorized: False
    max_users: -1
  htpasswd:
    file: ./htpasswd
#   # Maximum amount of users allowed to register, defaults to "+inf".
#   # You can set this to -1 to disable registration.
#   # currently used only for deployment accounts
    max_users: 2

# a list of other known repositories we can talk to

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@example/*':
    # scoped packages
    access: npm_example_access
    publish: npm_example_publisher

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

  '@*/*':
    # scoped packages
    access: npm_scope_root_access
    publish: npm_scope_root_publisher

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: npm_users

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: npm_users_publisher

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: debug}
  # - {type: file, path: /verdaccio.log, level: info}
web:
  enable: true
  title: Redacted
```

I have created one user with all group permissions and pushed 3 packages:

![image](https://user-images.githubusercontent.com/1866564/40114659-f158d3d0-5937-11e8-8d7a-13324e350597.png)

## I expect 

- To be able to manage group from ldap: FAIL
- Expect removing user from group `npm_users` should fail upon login: OK
- Expect removing user from all scoped group should hide view of scopped package: FAIL

## Question

- when are retrieved the group ? are they attached with the token? 
- is there a way to log the group of a user ?
