### ISSUE TITLE
[Bug][2.0.0] E403 when trying to npm install <name> --registry http://localhost:4873

### ISSUE THREAD

**Issue by kopax** [Alexandre-io/verdaccio-ldap#29]
## Expected

- **publish** with `npm install`.
- **access** with `npm install`.
- **access** with browser.

## Result

- **publish** with `npm install`: OK
- **access** with `npm install`: FAIL
- **access** with browser: OK

## Reproduction

**Version**:

- verdaccio: 2.7.4
- verdaccio-ldap: 2.0.0

`ldap/config.yml`:

```yml
storage: /verdaccio/storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldap://ldap.example.com"
      adminDn: "cn=admin,dc=example,dc=com"
      adminPassword: "example"
      searchBase: "dc=example,dc=com"
      searchFilter: "(&(uid={{username}})(memberOf=cn=npm_users,ou=npm,ou=groups,dc=example,dc=com))"
      groupDnProperty: 'cn'
      groupSearchBase: 'ou=npm,ou=groups,dc=example,dc=com'
      searchAttributes: ['*', 'memberOf']
      cache: False
      tlsOptions:
        rejectUnauthorized: False
    max_users: -1
  htpasswd:
    file: ./htpasswd
    max_users: 2
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@example/*':
    access: npm_example_access
    publish: npm_example_publisher
  '@example2/*':
    # scoped packages
    access: npm_example2_access
    publish: npm_example2_publisher
    proxy: npmjs
  '@*/*':
    access: npm_scope_root_access
    publish: npm_scope_root_publisher
    proxy: npmjs
  '**':
    access: npm_users
    publish: npm_users_publisher
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: debug}
web:
  enable: true
  title: npm example
```

I have created an user which is `memberOf` all the groups here.

I am able to login, to publish, to view in the UI the package, but when I do:

```bash
$ npm install mypackage-test --registry http://npm.example.com
```

I have 403 error:

```
npm ERR! code E403
npm ERR! 403 Forbidden: mypackage-test@latest
````
