### ISSUE TITLE
can not catch the invalid error

### ISSUE THREAD

**Issue by vegawong** [Alexandre-io/verdaccio-ldap#44]
Context:
verdaccio@3.7.1 & verdaccio@3.0.0
npm@5.6.0

config section:
```yaml
auth:
  ldap:
      type: ldap
      groupNameAttribute: 'cn'
      client_options:
        url: "serverName"
        adminDn: "cn=admin,dc=sever,dc=com"
        adminPassword: "***"
        searchBase: "ou=People,dc=server,dc=com"
        searchFilter: "(uid={{username}})"
        cache: False
        searchAttributes:
          - "*"
          - memberOf
        tlsOptions:
          rejectUnauthorized: False
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

```

Step:
1. clear htpasswd file and npmrc
2. excute `npm --registry=http://localhost:4874 login`
3. type wrong username & password
4. See verdaccio console but npmrc file was write
    ```
    warn --- LDAP error InvalidCredentialsError: Invalid Credentials
   ```
   and terminal console as 
  ```
  Logged in as userName on http://localhost:4873/
  ```
5. excute `npm --registry=http://localhost:4874 info react version`
6. the same verdaccio console as step4, and terminal console as 
    ```
    16.4.2
    ```
    it seams can use the invalid user to access the packages?
